// Code generated by togo. API Resource transformer for Post — customize
// the response shape here (Laravel-style API Resources). REST handlers return this.
package resources

import (
	"time"

	db "github.com/togo-framework/demo/internal/db/gen"
)

// PostResponse is the JSON shape returned by the Post API.
type PostResponse struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Body      *string   `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// TransformPost maps a db row to the API response. Edit freely.
func TransformPost(m db.Post) PostResponse {
	return PostResponse{
		ID:        m.ID,
		Title:     m.Title,
		Body:      m.Body,
		CreatedAt: m.CreatedAt,
		UpdatedAt: m.UpdatedAt,
	}
}

// TransformPosts maps a slice of db rows to API responses.
func TransformPosts(rows []db.Post) []PostResponse {
	out := make([]PostResponse, len(rows))
	for i, m := range rows {
		out[i] = TransformPost(m)
	}
	return out
}
