// Code generated by togo. Eloquent-style query entry for Post.
// Driver-agnostic (dialect from DB_DRIVER). Examples:
//
//	models.Posts(a).Find(ctx, id)
//	models.Posts(a).Where("title", "ILIKE", "%x%").Order("created_at DESC").Get(ctx)
package models

import (
	"github.com/togo-framework/orm"

	"github.com/togo-framework/demo/internal/app"
	db "github.com/togo-framework/demo/internal/db/gen"
)

// Posts starts a query against the posts table.
func Posts(a *app.App) *orm.Query[db.Post] {
	return orm.For[db.Post](a.SQLDB, a.Dialect, "posts")
}
