-- Code generated by togo. SQLite query fragment - safe to edit.
-- name: GetPost :one
SELECT * FROM posts WHERE id = ?;

-- name: ListPosts :many
SELECT * FROM posts ORDER BY created_at DESC LIMIT ? OFFSET ?;

-- name: CreatePost :one
INSERT INTO posts (title, body)
VALUES (?, ?)
RETURNING *;

-- name: DeletePost :exec
DELETE FROM posts WHERE id = ?;
