// Code generated by togo. REST (Huma) CRUD for posts via the ORM - safe to edit.
package rest

import (
	"context"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/togo-framework/validation"

	"github.com/togo-framework/demo/internal/app"
	"github.com/togo-framework/demo/internal/models"
	"github.com/togo-framework/demo/internal/resources"
)

// RegisterPostRoutes mounts CRUD endpoints for posts.
// Queries use the driver-agnostic ORM; responses go through resources.TransformPost;
// create/delete broadcast events ("post.created"/".deleted").
func RegisterPostRoutes(api huma.API, a *app.App) {
	huma.Register(api, huma.Operation{
		OperationID: "list-posts", Method: http.MethodGet, Path: "/api/posts",
		Summary: "List Posts", Tags: []string{"Post"},
	}, func(ctx context.Context, in *struct {
		Limit  int `query:"limit" default:"100"`
		Offset int `query:"offset"`
	}) (*struct {
		Body []resources.PostResponse
	}, error) {
		rows, err := models.Posts(a).Order("created_at DESC").Limit(in.Limit).Offset(in.Offset).Get(ctx)
		if err != nil {
			return nil, huma.Error500InternalServerError("list failed", err)
		}
		return &struct {
			Body []resources.PostResponse
		}{Body: resources.TransformPosts(rows)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "get-post", Method: http.MethodGet, Path: "/api/posts/{id}",
		Summary: "Get a Post", Tags: []string{"Post"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct {
		Body resources.PostResponse
	}, error) {
		row, err := models.Posts(a).Find(ctx, in.ID)
		if err != nil {
			return nil, huma.Error500InternalServerError("get failed", err)
		}
		if row == nil {
			return nil, huma.Error404NotFound("post not found")
		}
		return &struct {
			Body resources.PostResponse
		}{Body: resources.TransformPost(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "create-post", Method: http.MethodPost, Path: "/api/posts",
		DefaultStatus: http.StatusCreated, Summary: "Create a Post", Tags: []string{"Post"},
	}, func(ctx context.Context, in *struct {
		Body struct {
			Title string  `json:"title" validate:"required"`
			Body  *string `json:"body"`
		}
	}) (*struct {
		Body resources.PostResponse
	}, error) {
		// Request validation layer (Laravel-style rules from `validate` tags).
		if errs := validation.Validate(in.Body); errs.Any() {
			return nil, huma.Error422UnprocessableEntity(errs.Error())
		}
		row, err := models.Posts(a).Create(ctx, map[string]any{
			"title": in.Body.Title,
			"body":  in.Body.Body,
		})
		if err != nil {
			return nil, huma.Error500InternalServerError("create failed", err)
		}
		a.Emit(ctx, "post.created", row)
		return &struct {
			Body resources.PostResponse
		}{Body: resources.TransformPost(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "update-post", Method: http.MethodPut, Path: "/api/posts/{id}",
		Summary: "Update a Post", Tags: []string{"Post"},
	}, func(ctx context.Context, in *struct {
		ID   string `path:"id"`
		Body struct {
			Title string  `json:"title"`
			Body  *string `json:"body"`
		}
	}) (*struct {
		Body resources.PostResponse
	}, error) {
		if err := models.Posts(a).Where("id", "=", in.ID).Update(ctx, map[string]any{
			"title": in.Body.Title,
			"body":  in.Body.Body,
		}); err != nil {
			return nil, huma.Error500InternalServerError("update failed", err)
		}
		row, err := models.Posts(a).Find(ctx, in.ID)
		if err != nil || row == nil {
			return nil, huma.Error500InternalServerError("reload failed", err)
		}
		a.Emit(ctx, "post.updated", row)
		return &struct {
			Body resources.PostResponse
		}{Body: resources.TransformPost(*row)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "delete-post", Method: http.MethodDelete, Path: "/api/posts/{id}",
		DefaultStatus: http.StatusNoContent, Summary: "Delete a Post", Tags: []string{"Post"},
	}, func(ctx context.Context, in *struct {
		ID string `path:"id"`
	}) (*struct{}, error) {
		if err := models.Posts(a).Where("id", "=", in.ID).Delete(ctx); err != nil {
			return nil, huma.Error500InternalServerError("delete failed", err)
		}
		a.Emit(ctx, "post.deleted", in.ID)
		return &struct{}{}, nil
	})
}
