// Code generated by togo. DO NOT EDIT.
package rest

import (
	"github.com/danielgtaylor/huma/v2"

	"github.com/togo-framework/demo/internal/app"
)

// RegisterRoutes mounts every generated resource's REST routes. Regenerated from
// togo.resources.yaml on every make:* / generate.
func RegisterRoutes(api huma.API, a *app.App) {
	RegisterPostRoutes(api, a)
}
