// Code generated by togo. Data hook for Posts.
import useSWR from "swr";

import { apiFetch } from "@/lib/api/client";
import type { Post } from "@/lib/api/post";

export function usePosts() {
  return useSWR<Post[]>("/posts", apiFetch);
}
