// Code generated by togo. Factory — builds fake Posts via faker,
// persisted through the ORM. Used by seeders; customize the Definition freely.
package factories

import (
	"context"

	"github.com/togo-framework/faker"

	"github.com/togo-framework/demo/internal/app"
	db "github.com/togo-framework/demo/internal/db/gen"
	"github.com/togo-framework/demo/internal/models"
)

// PostFactory builds fake Post records.
type PostFactory struct {
	app   *app.App
	count int
}

// Posts starts a factory for Posts.
func Posts(a *app.App) *PostFactory {
	return &PostFactory{app: a, count: 1}
}

// Count sets how many records Create() will make.
func (f *PostFactory) Count(n int) *PostFactory { f.count = n; return f }

// Definition returns fake attributes for one Post. Edit to taste.
func (f *PostFactory) Definition() map[string]any {
	_ = faker.Word
	return map[string]any{
		"title": faker.Name(),
		"body":  faker.Paragraph(),
	}
}

// Create builds and persists Count records via the ORM.
func (f *PostFactory) Create(ctx context.Context) ([]db.Post, error) {
	out := make([]db.Post, 0, f.count)
	for i := 0; i < f.count; i++ {
		row, err := models.Posts(f.app).Create(ctx, f.Definition())
		if err != nil {
			return out, err
		}
		out = append(out, *row)
	}
	return out, nil
}
