// Code generated by togo. Next.js page for Posts.
"use client";

import { usePosts } from "@/lib/hooks/usePosts";

export default function PostsPage() {
  const { data, isLoading } = usePosts();
  if (isLoading) return <p>Loading…</p>;
  return (
    <main className="p-6">
      <h1 className="text-2xl font-bold">Posts</h1>
      <ul>
        {data?.map((item) => (
          <li key={item.id}>{item.id}</li>
        ))}
      </ul>
    </main>
  );
}
