// Code generated by togo. GraphQL resolvers for Post via the ORM — safe to edit.
package resolvers

import (
	"context"

	db "github.com/togo-framework/demo/internal/db/gen"
	graphgen "github.com/togo-framework/demo/internal/graph/gen"
	"github.com/togo-framework/demo/internal/models"
)

func (r *queryResolver) Post(ctx context.Context, id string) (*db.Post, error) {
	return models.Posts(r.App).Find(ctx, id)
}

func (r *queryResolver) Posts(ctx context.Context) ([]*db.Post, error) {
	rows, err := models.Posts(r.App).Order("created_at DESC").Limit(100).Get(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*db.Post, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

func (r *mutationResolver) CreatePost(ctx context.Context, input graphgen.CreatePostInput) (*db.Post, error) {
	row, err := models.Posts(r.App).Create(ctx, map[string]any{
		"title": input.Title,
		"body":  input.Body,
	})
	if err != nil {
		return nil, err
	}
	r.App.Emit(ctx, "post.created", row)
	return row, nil
}

func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	if err := models.Posts(r.App).Where("id", "=", id).Delete(ctx); err != nil {
		return false, err
	}
	r.App.Emit(ctx, "post.deleted", id)
	return true, nil
}
