-- Code generated by togo. SQLite schema fragment for sqlc and migrate.
CREATE TABLE IF NOT EXISTS posts (
    id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    title text NOT NULL,
    body text,
    created_at datetime NOT NULL DEFAULT (datetime('now')),
    updated_at datetime NOT NULL DEFAULT (datetime('now'))
);
