// Code generated by togo (seeder) — uses the factory; adjust the count freely.
package seeders

import (
	"context"

	"github.com/togo-framework/demo/internal/app"
	"github.com/togo-framework/demo/internal/factories"
)

// SeedPost inserts fake Posts via the factory.
func SeedPost(ctx context.Context, a *app.App) error {
	_, err := factories.Posts(a).Count(5).Create(ctx)
	return err
}
