// Code generated by togo. DO NOT EDIT.
package seeders

import (
	"context"

	"github.com/togo-framework/demo/internal/app"
)

// SeedAll runs every resource seeder. Regenerated from togo.resources.yaml.
func SeedAll(ctx context.Context, a *app.App) error {
	if err := SeedPost(ctx, a); err != nil {
		return err
	}
	return nil
}
